### ISSUE TITLE
 Question

### ISSUE THREAD

**Issue by npacoder** [kryptokrona/hugin-cache#104]
Hello. Do you have a repo that handles user authentication via jwt?

**Comment by mjovanc** [comment]
@npacoder No we do not currently have user authentication yet for Hugin Cache. Is this something that you need to host it? In that case, then we can consider implementing that.

**Comment by npacoder** [comment]
@mjovanc 
I stumbled across this project while exploring github and found your code to be very clean & easy to understand.

By the way would like to see how to write your code for functions like: jwt if you've ever done it. Other than that, no problem. Have a nice day buddy.

**Comment by mjovanc** [comment]
@npacoder Thanks a lot! I have not unfortunately. We will probably do it a little bit different here since we can validate through the blockchain instead of using JWT of similar authentication methods. 

Have a nice day you too! If you are interested in blockchain feel free to join our Discord: https://discord.gg/mkRpVgDubC
