### ISSUE TITLE
Change to UNIX timestamps instead of UTC format

### ISSUE THREAD

**Issue by f-r00t** [kryptokrona/hugin-cache#187]
Seeing as the rest of the Hugin codebase uses unix timestamps for everything, it would make things a lot easier if we used timestamps for startDatge and endDate parameters on the cache as well.

**Comment by mjovanc** [comment]
The problem I see is that it can not cover timezone information in a unix timestamp? https://stackoverflow.com/questions/23062515/do-unix-timestamps-change-across-timezones

**Comment by f-r00t** [comment]
Unix timestamps, as your link describes, are timezone agnostic. 1661191200 is the same moment everywhere on Earth. How you want to display a timestamp, however, is an issue for the client side. We use moment.js to do that for us for most apps.

**Comment by mjovanc** [comment]
Why don't you use in the standard library Date()? Just curious. Easy to parse from our current created_at timestamp?

**Comment by f-r00t** [comment]
Mostly because I want the timedelta in a nice presentable format, such as "Two hours ago", which Moment.js handles really well. Again, it's completely possible to convert the UTC format to unix timestamps and vice versa, but again it would be nice to use the same format everywhere (hitherto we've been using unix timestamps).

**Comment by mjovanc** [comment]
Let's do it. Read more upon it and read your comments, I now see some valid reasons for it. Just wanted some more concrete reasons to switch since this might effects everyone using Hugin Cache currently. Although not too many at this point, but I will soon start working on strategy of different API versions so we can do more bigger changes and the old versions can still exist and work.

Just wanted to ping you @Swepool as well on this change so you are on board with this as well and changes that might be required by you to fix.

**Comment by mjovanc** [comment]
Implemented in https://github.com/kryptokrona/hugin-cache/commit/530ce5112ff3f7db883074f3e71f9917489ab8ae. Will see if it passes the workflow.

**Comment by mjovanc** [comment]
Fixed.
